---
abstract: 'REST model class for Dancer apps'
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-RESTModel
no_index:
  directory:
    - t
    - inc
requires:
  Dancer: 0
  Moose: 0
  Role::REST::Client: 0
  Test::More: 0.88
version: 0.01
